# Generated by Django 6.0.1 on 2026-01-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
