# Generated by Django 6.0.1 on 2026-01-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_product_id_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
