# Generated by Django 6.0.1 on 2026-01-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salepayment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salepayment',
            table='sale_payments',
        ),
    ]
