# Generated by Django 6.0.1 on 2026-01-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
