# Generated by Django 6.0.1 on 2026-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cnpj_cpf',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
